[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
multi_delegator = "9GjJt2mJXY9szY7TyfKqBpbb8Nc95vgjnRenXZWX17xH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
